/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoterResourcesRouteImport } from './routes/voter-resources'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const VoterResourcesRoute = VoterResourcesRouteImport.update({
  id: '/voter-resources',
  path: '/voter-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/voter-resources': typeof VoterResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/voter-resources': typeof VoterResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/voter-resources': typeof VoterResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/cookie-policy'
    | '/events'
    | '/gallery'
    | '/membership'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/voter-resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/cookie-policy'
    | '/events'
    | '/gallery'
    | '/membership'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/voter-resources'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/cookie-policy'
    | '/events'
    | '/gallery'
    | '/membership'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/voter-resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VoterResourcesRoute: typeof VoterResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voter-resources': {
      id: '/voter-resources'
      path: '/voter-resources'
      fullPath: '/voter-resources'
      preLoaderRoute: typeof VoterResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  MembershipRoute: MembershipRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VoterResourcesRoute: VoterResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
